## Линейная алгебра ч.1
http://immersivemath.com/ila/learnmore.html

### Вектор:
* в школьной геометрии - направленный отрезок
* в линейной алгебре - элемент векторного пространства
* в python - числовой массив (например Numpy)

Определение:
- Вектор это набор чисел записанный в определенном порядке в столбик или в строчку.

В качестве примера рассмотрим регистр учет затрат. Столбцы мы можем рассмотреть в качестве векторов, получив информацию о каждой хозяйственной операции по одному параметру, например по стоимости. Если взять в качестве векторов строки, то мы увидим срез всех параметров по одной операции. 

Основные характеристики вектора:
- Координаты вектора - числа из которых он состоит
- Размерность вектора - количество координат

### Задача из жизни
Агентство недвижимости выставило за неделю несколько квартир площадью 33, 65, 50 и 45 кв м. Сколько всего квартир выставлено за неделю? Какова площадь квартиры номер 3?

In [1]:
# Решение:

# Задаем наш вектор как одномерный массив numpy

import numpy as np
s = np.array([33, 65, 50, 45])
print(s[2])
print(len(s))

50
4


Чтобы иметь возможность математически или даже программно оперировать сущностями нашего мира, нам нужно их упростить до формы понятной компьютеру. Признаковое описание объектов реального мира в виде чисел - это и есть то самое упрощение.

Анализируя потенциальную стоимость определенной квартиры, мы будем иметь в виду следующие признаки:
- общая площадь квартиры в квадратных метрах
- этаж квартиры
- количество комнат
- цена квартиры за квадратный метр
- количество подъездов в доме


рассмотрим предложение на покупку.

На рынке новостроек появилось предложение от застройщика - двухкомнатная квартира общей плщадью 59.50 кв.м, жилой плщадью 31.40 кв.м на 19 этаже 22-х этажного дома. В доме 2 подъезда. Цена за квадратный метр квартиры у этого застройщика составляет 60550

Таким образом мы можем описать нашу квартиру числовой последовательностью важных для нас признаков при покупке квартиры.

In [2]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

Эта последовательность чисел и называется вектором. Вектором характеризует конкретный объект - конкретную квартиру. А число в той или иной позиции вектора описывает конкретный признак объекта. То есть вектор - это, по сути, одномерный массив.

In [3]:
# В NumPy вектор и массив - одно и то же.
# Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы,
# где один из атрибутов shape равен 1
print("ndim:",apartment.ndim)
print("shape",apartment.shape)

ndim: 1
shape (6,)


попробуем извлечь полезную информацию из вектора, при этом уменьшив его.

Упростим себе задачу оценки новой квартиры  - сгенерируем новый признак - отношение жилой площади к общей. А от старых признаков смело избавимся, сократив векторное пространство нашего объекта.

Возьмем квартиру из описания выше и представим ее неким вектором apartment

In [8]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

Для того, чтобы сгенерировать новый параметр share_living_space (доля жилой площади в квартире) из старых признаков, содержащихся в векторе-описании apartment нашей квартиры, нам необходимо вспомнить обращение к элементам массива. Разделим значение жилой площади на ее общее количество:

In [9]:
share_living_space = apartment[1]/apartment[0]

избавимся от старых признаков, посредством функции delete(), которую предоставляет бибилиотека numpy. Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment

In [11]:
apartment = np.delete(apartment,[0,1])
apartment

array([6.055e+04, 2.000e+00])

In [27]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment,[0,1])
np.append(apartment, share_living_space)
# apartment[3:4]
share_living_space

0.5277310924369748

In [28]:
# 1.2.3

t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

Ссылки на Numpy:
- https://habr.com/ru/post/352678/
- https://habr.com/ru/post/353416/
- https://habr.com/ru/post/413381/



## Сложение векторов
Сложение векторов происходит поэлементно

Задача.
За текущую неделю просмотры по четырем квартирам составили 10, 8, 5 и 1 раз, а за предыдущую 5, 15, 9 и 7 раз соответственно. Найдите суммарное количество просмотров за 2 недели. Найдите разницу в просмотрах по каждой квартире за 2 недели.

In [31]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
print(a - b)

[15 23 14  8]
[ 5 -7 -4 -6]


### Умножение вектора на число
Умножение вектора на число так же происходит поэлементно, то есть каждая координата вектора умножается на заданное число.

Задача

Найдите произведение вектора а = [120, 45, 68] и числа 0.2

In [32]:
a = np.array([120, 45, 68])
c = a * 0.2
c

array([24. ,  9. , 13.6])

Векторы a и c пропорциональны друг другу с коэффициентом 0.2 Такие векторы так же называют коллинеарными.

In [34]:
#1.3.2
x = np.array([5, 2])
y = np.array([-5, -11])
print('s =', x + y)
print('d =', x - y)

s = [ 0 -9]
d = [10 13]


In [35]:
#1.3.3
a = np.array([120, 150, 90])
w = np.array([130, 130, 130])
g = np.array([2, 3, 2.5])
rate = 72

g_profit = g * rate
all_profit = a + w + g_profit
print('g_profit', g_profit)
print('all_profit', all_profit)

g_profit [144. 216. 180.]
all_profit [394. 496. 400.]


### Линейная комбинация векторов
Линейная комбинация это объединение двух предыдущих операций в одну: каждый вектор умножается на соответствующий ему коэффициент, все умноженные векторы складываются.
#### Определение
Линейная комбинация - это сумма векторов, умноженных на некоторые числа.

Пример:

Найдите линейную комбинацию трех заданных векторов p = [2,4,5], v = [8, 10, 2], s = [0, 12, 7] с коэффициентами 500, 100 и 0

In [36]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])

m = 500 * p + 100 * v + 0 * s
print(m)

[1800 3000 2700]


### Нулевая линейная комбинация
Самое интересное в линейных комбинциях - это особые случаи.

Из заданного набора векторов можно получить нулевую линейную комбинацию, умножив каждый вектор на ноль. Такие комбинации называются тривиальными.

#### Определение:
Линейная комбинация называется тривиальной, если все коэффициенты равны нулю. (Сумма векторов умноженная на некоторые числа называется тривиальной, если все коэффициенты равны нулю)

Далее мы будем рассматривать только нетривиальные линейные комбинации, в которых не все коэффициенты равны нулю

#### Определение:
Линейная комбинация называется нетривиальной, если хотя бы один из коэффициентов не равен нулю.

### Можно ли получить нулевой вектор?:
- Да
Пусть из заданного набора векторов нам удалось составить нулевую нетривиальную линейную комбинацию.

#### Определение:
Векторы называются линейно зависимыми, если существует нулевая нетривиальная комбинация этих векторов

- Нет
Вариант второй, пусть из заданного набора векторов нам не удалось составить нулевую нетривиальную линейную комбинацию.
#### Определение:
Векторы называются линейно независимыми, если не существует нулевой нетривиальной комбинации этих векторов.

При этом ни один вектор не выражается через другие векторы.

Пример 1

Можно ли представить вектор x = [3, 4, 0] в виде линейной комбинации векторов a = [1, 1, 0] & b = [1, 2, 0]

Решение:

Легко заметить, что удвоенный первый вектор + второй дают ровно вектор x


In [40]:
# 1.4.1
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])
print(2 * x + (-3) * y + 5 * u)
m = [2, -3, 5]
# print(np.array([x, y, u]) * m)

[7 7]


In [41]:
# 1.4.2
prod = np.array([3, 4, 5, 9])
sales = np.array([1, 5, 3, 6])
print(-200 * prod + 400 * sales)

[-200 1200  200  600]


In [46]:
# @Илья
v0 = np.array([-3, -2])
v1 = np.array([1, 1])
v2 = np.array([4, 3])

c0 = 1
c1 = -1
c2 = 1

v0 * c0 + v1 * c1 + v2 * c2

array([0, 0])

## 1.5 Скалярное произведение векторов
Существует 4 основных способа умножить векторы:
1. Скалярное произведение. Результат - число.
2. Векторное произведение. Результат - вектор.
3. Смешанное произведение. Результат - число.
4. Тензорное произведение. Результат - матрица.

Чтобы найти скалярное произведение двух векторов, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится.

Пример

Найти скалярное произведение векторов a=[65, 70, 120, 30] & w=[0.4, 0.4, 0.2, 0.8]

Решение:
(a[0] * w[0]) + (a[1] * w[1]) + (a[2] * w[2]) + (a[3] * w[3])

In [44]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
print(a[0]*w[0] + a[1]*w[1] + a[2]*w[2] + a[3]*w[3])
np.dot(a,w)

102.0


102.0

Задача из жизни:

Агент за неделю закрыл 4 сделки на суммы 65, 70, 120 и 30 т.р. Комиссия по каждой составила 40%, 40%, 20% и 80% соответственно. Сколько заработал агент за эти 4 сделки.

### Длина вектора
Для приложений нам так же понадобится вычислять длину вектора.

Длина вектора вычисляется как квадратный корень из скалярного произведения вектора с самим собой. Для нас это просто корень из суммы квадратов координат, как в теореме Пифагора - для случая с размерностью вектора равной двум (геометрически это длина отрезка).

Пример:

Найти длину векторов a = [3, 4], b = [-1, 1, 2, 0]

In [48]:
a = np.array([3, 4])
(np.dot(a, a)) ** 0.5

5.0

In [91]:
b = np.array([-1, 1, 2, 0])
(np.dot(b, b)) ** 0.5

2.449489742783178

In [50]:
6 ** 0.5

2.449489742783178

Чтобы получить длину вектора понятное дело вовсе не нужно проделывать всю эту хуиту. Для этого поняттное дело в numpy есть специальный метод.

In [92]:
l = np.linalg.norm(b)
l

2.449489742783178

### Особый случай. Ортогональность векторов
Векторы называются ортогональными, если их скалярное произведение равно нулю.

Пример

Найти скалярное произведение векторов (2, 3) и (-9, 6) Что означает полученный результат?

In [51]:
a = np.array([2, 3])
b = np.array([-9, 6])
a * b

array([-18,  18])

In [52]:
np.dot(a, b)

0

In [53]:
x = np.array([4, 5, -1])
y = np.array([2, 0, 1])
np.dot(x, y)

7

In [54]:
# 1.5.4
x = np.array([4, 6, 1])
(np.dot(x, x)) ** 0.5

7.280109889280518

In [57]:
# 1.5.5
# Какие пары векторов являются ортогональными?
x = np.array([4, 2, -1])
y = np.array([2, 0, 1])
print(1 if np.dot(x,y) == 0 else 0)

x = np.array([4, 5, -1])
y = np.array([0, 0, 0])
print(1 if np.dot(x,y) == 0 else 0)

x = np.array([4, -1])
y = np.array([-1, 4])
print(1 if np.dot(x,y) == 0 else 0)

x = np.array([4,-1])
y = np.array([1, 4])
print(1 if np.dot(x,y) == 0 else 0)

0
1
0
1


## 1.6. Векторы. Практическая задача.
Агентство "Рай в шалаше" недавно сдало 4 квартиры в одном доме. 
Общая площадь квартир: 33, 42, 33 и 65 кв м. 
Жилая площадь: 24, 32, 20, 48
Арендная плата: 39, 50, 38, 77

В том же доме появилась новая квартира общей площадью 50 кв м., из которых жилая - 40 кв м.

На основе имеющихся данных выберите оптимальную арендную плату для новой квартиры.

In [59]:
total = np.array([33, 42, 33, 65])
living = np.array([24, 32, 20, 48])
price = np.array([39, 50, 38, 77])

Нам нужно порекомендовать для новой квартиры оптимальную арендную плату, исходя из опыта предыдущих 4 квартир. Ключем к решению является линейная зависимость векторов: можно заметить, что price линейно выражается через total_area + 0.25 * living_area (Интересно как это блядь можно заметить?)

Задача (условие №2)

Пусть во второй квартире обнаружились тараканы, и ее пришлось сдать дешевле: за 48460 рублей, а в первой и третьей квартирах был застеклен балкон, и их удалось сдать дороже: за 40 000 и за 39 000 рублей.

Теперь вектор арендной платы не выражается линейно через векторы площадей.

In [60]:
total = np.array([33, 42, 33, 65])
living = np.array([24, 32, 20, 48])
price = np.array([40, 48.46, 39, 77])

Скалярное произведение равно нулю, это значит, что угол между векторами price и вектором разницы в цене... Нихуя не понятно.

Это значит, что среди всех возможных линейных комбинаций векторов общей и жилой площади наш изначальный price - наилучший прогноз арендной платы. Другими словами, если другой информации нет, то 60 тысяч рублей, которые мы получили в первом условии задачи и есть наш лучший прогноз стоимости аренды новой квартиры.

**Резюмируем:**
мы построили простейшую линейную регрессию стоимости аренды жилья по зашумленным данным, представленным в векторе 

**Задача (условие №3)**
<...> Пусть появилась дополнительная информация - нежилая площадь. Позволит ли она улучшить прогноз по аренде новой квартиры?

Нихуя!!!



**Нормирование вектора** - получение вектора с тем же направлением, что и исходный, но с нормой 1.

**Норма** вектора вычисляется как корень из суммы квадратов его компонент.

In [62]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})


In [70]:
# 1.7.1
display(Hut_Paradise_DF.loc[4])
display(Hut_Paradise_DF.values[4:5])



1.Rent              40
2.Area              33
3.Rooms              1
4.Floor              6
5.Demo two weeks    20
6.Liv.Area          16
Name: 4, dtype: int64

array([[40, 33,  1,  6, 20, 16]])

In [73]:
# 1.7.2
Hut_Paradise_DF['4.Floor'].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [75]:
# 1.7.4
Hut_Paradise_DF.count()

1.Rent              9
2.Area              9
3.Rooms             9
4.Floor             9
5.Demo two weeks    9
6.Liv.Area          9
dtype: int64

In [76]:
# 1.7.5
Hut_Paradise_DF['2.Area'].values - Hut_Paradise_DF['6.Liv.Area'].values

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [81]:
# 1.7.6
Hut_Paradise_DF['1.Rent'].values * 4 / 10

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [82]:
# 1.7.7
dur = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
np.dot(dur,Hut_Paradise_DF['5.Demo two weeks'].values)

1348

In [83]:
u = np.array([3, 0, 1, 1, 1])
v = np.array([0, 1, 0, 2, -2])
w = np.array([1, -4, -1, 0, -2])

In [88]:
# 1.7.8
# Линейная комбинация - умножение на чилсо и сложение
c = v * 2 + w * (-3)
display(c)

array([-3, 14,  3,  4,  2])

In [89]:
# 1.7.9
# Векторы называются ортогональными если их скалярное произведение равно 0
np.dot(c, u)

0

**Нормировка** - вектор деленный на его длину.
(Длину вектора можно получить методом numpy - np.linalg.norm(v))

In [94]:
# 1.7.10
u_norm = u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)

print(u_norm[2])
print(v_norm[3])
print(w_norm[0])

0.2886751345948129
0.6666666666666666
0.21320071635561041


# 1.8 Матрицы

## Основные понятия

**Определение:**

Матрица представляет собой набор чисел, расположенных по строкам и столбцам, как в таблице.

Матрицу можно создать командой **.matrix** или **.array**. Размер матрицы можно получить обратившись к свойству **shape**.

Помним, что матрицы, как и массивы индексируются с 0. Поэтому для вызова a23 нужно обратиться к элементу матрицы с номерами 12

In [95]:
# Example
import numpy as np
A = np.array([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [96]:
A.shape

(4, 3)

In [97]:
# Transposition
import numpy as np
A = np.matrix("1,-5;2,2;0,3")
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [98]:
A.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

In [99]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [100]:
# 1.9.1
import numpy as np
A = np.matrix("1,1;5,7")
B = np.matrix("6,1;-5,5")
A + B

matrix([[ 7,  2],
        [ 0, 12]])

* Диагональная матрица является инвариантом транспонирования.
* Если вычесть из диагональной матрицы единичную, поменяется только главная диагональ.
* Все столбцы диагональной матрицы ортогональны друг другу.

## 1.10 Практика. Базовые действия над матрицами

In [101]:
import numpy as np

In [103]:
# Как двумерный массив numpy
np.array([[1,1],[2,3],[4,5]])

array([[1, 1],
       [2, 3],
       [4, 5]])

In [104]:
# Преобразование из pandas dataframe
import pandas as pd

data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('dataframe:')
display(df)
print('matrix:')
display(A)

dataframe:


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

matrix:


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [105]:
# размер матрицы

print('np.shape(A)')
print(np.shape(A))
print('A.shape')
print(A.shape)

np.shape(A)
(4, 3)
A.shape
(4, 3)


In [106]:
# вектор-столбец
x = np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [107]:
x.reshape(1,3)

array([[1, 2, 3]])

In [108]:
x

array([1, 2, 3])

In [109]:
# Индексация матриц (двумерных массивов numpy)
print('матрица А')
print(A)
print('the first row of a matrix A:')
print(A[0])
print('the third column of a matrix A')
print(A[:,2])
print('item a_43')
print(A[3,2])

матрица А
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
the first row of a matrix A:
[1 2 3]
the third column of a matrix A
[ 3  6  9 12]
item a_43
12


In [110]:
# Creating of special matrix

In [111]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
# Диагональная
diagonal = [1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [115]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [116]:
Husband_income = np.array([100,220,140])
Wife_income = np.array([150,200,130])
Lover_income = np.array([90,80,100])

Husband_consumption = np.array([50,50,60])
Wife_consuption = np.array([100,80,140])
Lover_consumption = np.array([100,20,140])


In [117]:
np.array([100,150,90])*0.87

array([ 87. , 130.5,  78.3])

In [120]:
income = np.array([Husband_income, Wife_income, Lover_income]).T
income

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [122]:
P = income * 0.87
P

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [124]:
consumption = np.array([Husband_consumption, Wife_consuption, Lover_consumption]).T
consumption

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [126]:
income * 0.87 - consumption

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

## Умножение матриц

In [127]:
import numpy as np
A = np.matrix("1,-5;2,2;0,3")
B = np.matrix("3,1,0;-1,0, 2")

In [128]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [129]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [130]:
np.dot(A,B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [131]:
np.dot(B,A)

matrix([[  5, -13],
        [ -1,  11]])